// incremental_pr — Dry-run skill that plans branches and PRs for incremental migration tasks

import type { Skill } from "./index.js";

export interface IncrementalPrInput {
  repoPath: string;
  forkOwner: string;
  forkRepo: string;
  baseBranch?: string;
  tasks: Array<{
    id: string;
    title: string;
    description: string;
    filePaths: string[];
  }>;
}

export interface PullRequestEntry {
  taskId: string;
  branchName: string;
  title: string;
  body: string;
  status: "created" | "dry-run" | "failed";
  error?: string;
}

export interface IncrementalPrOutput {
  pullRequests: PullRequestEntry[];
  stats: {
    total: number;
    created: number;
    failed: number;
  };
}

/** Sanitize a task id into a valid git branch segment. */
export function sanitizeBranchName(taskId: string): string {
  return taskId
    .replace(/[^a-zA-Z0-9_/-]/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function buildBranchName(taskId: string): string {
  return `jurassic/${sanitizeBranchName(taskId)}`;
}

export function buildPrTitle(taskTitle: string): string {
  return `[Jurassic] ${taskTitle}`;
}

export function buildPrBody(task: {
  description: string;
  filePaths: string[];
}): string {
  const fileList = task.filePaths.map((f) => `- \`${f}\``).join("\n");
  return [
    "## Description",
    "",
    task.description,
    "",
    "## Changed Files",
    "",
    fileList,
    "",
    "---",
    "*Auto-generated by Jurassic incremental_pr skill.*",
  ].join("\n");
}

function validateInput(context: unknown): IncrementalPrInput {
  const input = context as IncrementalPrInput;
  if (!input || typeof input !== "object") {
    throw new Error("incremental_pr: context must be an object");
  }
  if (!input.forkOwner || typeof input.forkOwner !== "string") {
    throw new Error("incremental_pr: forkOwner is required");
  }
  if (!input.forkRepo || typeof input.forkRepo !== "string") {
    throw new Error("incremental_pr: forkRepo is required");
  }
  if (!Array.isArray(input.tasks)) {
    throw new Error("incremental_pr: tasks must be an array");
  }
  return input;
}

export const incrementalPrSkill: Skill = {
  name: "incremental_pr",

  async execute(context: unknown): Promise<IncrementalPrOutput> {
    const input = validateInput(context);
    const tasks = input.tasks;

    if (tasks.length === 0) {
      return { pullRequests: [], stats: { total: 0, created: 0, failed: 0 } };
    }

    const pullRequests: PullRequestEntry[] = tasks.map((task) => ({
      taskId: task.id,
      branchName: buildBranchName(task.id),
      title: buildPrTitle(task.title),
      body: buildPrBody(task),
      status: "dry-run" as const,
    }));

    return {
      pullRequests,
      stats: {
        total: pullRequests.length,
        created: pullRequests.filter((pr) => pr.status === "created").length,
        failed: pullRequests.filter((pr) => pr.status === "failed").length,
      },
    };
  },
};
