// pr_writer — Skill that creates PRs with code changes from approved modernization plans

import type { Skill } from "./index.js";

export interface FileChange {
  path: string;
  content: string;
  changeType: "create" | "modify" | "delete";
}

export interface PrWriterInput {
  forkOwner: string;
  repoName: string;
  baseBranch: string;
  taskId: string;
  taskDescription: string;
  fileChanges: FileChange[];
  artifactIds?: string[];
  riskItems?: Array<{ id: string; severity: string; description: string }>;
  recommendations?: string[];
  dryRun?: boolean;
}

export interface PrWriterOutput {
  prNumber?: number;
  prUrl?: string;
  branchName: string;
  title: string;
  body: string;
  fileCount: number;
  status: "created" | "dry-run" | "failed";
  error?: string;
}

export function buildBranchName(taskId: string): string {
  const sanitized = taskId
    .replace(/[^a-zA-Z0-9_/-]/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
  return `jurassic/task-${sanitized}`;
}

export function buildPrTitle(taskDescription: string): string {
  return `[Jurassic] ${taskDescription}`;
}

export function buildPrBody(input: {
  taskDescription: string;
  fileChanges: FileChange[];
  artifactIds?: string[];
  riskItems?: Array<{ id: string; severity: string; description: string }>;
  recommendations?: string[];
}): string {
  const sections: string[] = [];

  // Changes section
  const fileList = input.fileChanges
    .map((f) => `- \`${f.path}\` (${f.changeType})`)
    .join("\n");
  sections.push("## Changes", "", input.taskDescription, "", fileList || "_No file changes._");

  // Artifacts section
  if (input.artifactIds && input.artifactIds.length > 0) {
    const ids = input.artifactIds.map((id) => `- \`${id}\``).join("\n");
    sections.push("", "## Artifacts Referenced", "", ids);
  }

  // Risk items section
  if (input.riskItems && input.riskItems.length > 0) {
    sections.push("", "## Risk Items", "");
    sections.push("| ID | Severity | Description |");
    sections.push("| --- | --- | --- |");
    for (const risk of input.riskItems) {
      sections.push(`| ${risk.id} | ${risk.severity} | ${risk.description} |`);
    }
  }

  // Recommendations section
  if (input.recommendations && input.recommendations.length > 0) {
    const recs = input.recommendations.map((r) => `- ${r}`).join("\n");
    sections.push("", "## Recommendations", "", recs);
  }

  // Footer
  sections.push("", "---", "*Generated by Jurassic Modernization Agent*");

  return sections.join("\n");
}

/** Create a branch on the fork. Override in tests for mocking. */
export async function createBranch(
  _owner: string,
  _repo: string,
  _branchName: string,
  _baseBranch: string,
): Promise<void> {
  // In production, calls GitHub MCP create_branch tool
}

/** Push file changes to the branch on the fork. Override in tests for mocking. */
export async function pushFiles(
  _owner: string,
  _repo: string,
  _branchName: string,
  _files: FileChange[],
): Promise<void> {
  // In production, calls GitHub MCP push_files tool
}

/** Create a pull request from the fork branch to the upstream base. Override in tests for mocking. */
export async function createPullRequest(
  _owner: string,
  _repo: string,
  _title: string,
  _body: string,
  _head: string,
  _base: string,
): Promise<{ prNumber: number; prUrl: string }> {
  // In production, calls GitHub MCP create_pull_request tool
  return { prNumber: 0, prUrl: "" };
}

function validateInput(context: unknown): PrWriterInput {
  const input = context as PrWriterInput;
  if (!input || typeof input !== "object") {
    throw new Error("pr_writer: context must be an object");
  }
  if (!input.forkOwner || typeof input.forkOwner !== "string") {
    throw new Error("pr_writer: forkOwner is required");
  }
  if (!input.repoName || typeof input.repoName !== "string") {
    throw new Error("pr_writer: repoName is required");
  }
  if (!input.taskId || typeof input.taskId !== "string") {
    throw new Error("pr_writer: taskId is required");
  }
  if (!input.taskDescription || typeof input.taskDescription !== "string") {
    throw new Error("pr_writer: taskDescription is required");
  }
  if (!Array.isArray(input.fileChanges)) {
    throw new Error("pr_writer: fileChanges must be an array");
  }
  return input;
}

export const prWriterSkill: Skill = {
  name: "pr_writer",

  async execute(context: unknown): Promise<PrWriterOutput> {
    const input = validateInput(context);

    const branchName = buildBranchName(input.taskId);
    const title = buildPrTitle(input.taskDescription);
    const body = buildPrBody({
      taskDescription: input.taskDescription,
      fileChanges: input.fileChanges,
      artifactIds: input.artifactIds,
      riskItems: input.riskItems,
      recommendations: input.recommendations,
    });
    const fileCount = input.fileChanges.length;

    if (input.dryRun) {
      return {
        branchName,
        title,
        body,
        fileCount,
        status: "dry-run",
      };
    }

    try {
      await createBranch(input.forkOwner, input.repoName, branchName, input.baseBranch);
      await pushFiles(input.forkOwner, input.repoName, branchName, input.fileChanges);
      const { prNumber, prUrl } = await createPullRequest(
        input.forkOwner,
        input.repoName,
        title,
        body,
        `${input.forkOwner}:${branchName}`,
        input.baseBranch,
      );

      return {
        prNumber,
        prUrl,
        branchName,
        title,
        body,
        fileCount,
        status: "created",
      };
    } catch (err) {
      return {
        branchName,
        title,
        body,
        fileCount,
        status: "failed",
        error: err instanceof Error ? err.message : String(err),
      };
    }
  },
};
