// pr_writer — Skill that creates PRs with code changes from approved modernization plans

import { Octokit } from "@octokit/rest";
import type { Skill } from "./index.js";

export interface FileChange {
  path: string;
  content: string;
  changeType: "create" | "modify" | "delete";
}

export interface PrWriterInput {
  forkOwner: string;
  repoName: string;
  baseBranch: string;
  taskId: string;
  taskDescription: string;
  fileChanges: FileChange[];
  artifactIds?: string[];
  riskItems?: Array<{ id: string; severity: string; description: string }>;
  recommendations?: string[];
  dryRun?: boolean;
}

export interface PrWriterOutput {
  prNumber?: number;
  prUrl?: string;
  branchName: string;
  title: string;
  body: string;
  fileCount: number;
  status: "created" | "dry-run" | "failed";
  error?: string;
  confidence: number;
}

export function buildBranchName(taskId: string): string {
  const sanitized = taskId
    .replace(/[^a-zA-Z0-9_/-]/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");
  return `jurassic/task-${sanitized}`;
}

export function buildPrTitle(taskDescription: string): string {
  return `[Jurassic] ${taskDescription}`;
}

export function buildPrBody(input: {
  taskDescription: string;
  fileChanges: FileChange[];
  artifactIds?: string[];
  riskItems?: Array<{ id: string; severity: string; description: string }>;
  recommendations?: string[];
}): string {
  const sections: string[] = [];

  // Changes section
  const fileList = input.fileChanges
    .map((f) => `- \`${f.path}\` (${f.changeType})`)
    .join("\n");
  sections.push("## Changes", "", input.taskDescription, "", fileList || "_No file changes._");

  // Artifacts section
  if (input.artifactIds && input.artifactIds.length > 0) {
    const ids = input.artifactIds.map((id) => `- \`${id}\``).join("\n");
    sections.push("", "## Artifacts Referenced", "", ids);
  }

  // Risk items section
  if (input.riskItems && input.riskItems.length > 0) {
    sections.push("", "## Risk Items", "");
    sections.push("| ID | Severity | Description |");
    sections.push("| --- | --- | --- |");
    for (const risk of input.riskItems) {
      sections.push(`| ${risk.id} | ${risk.severity} | ${risk.description} |`);
    }
  }

  // Recommendations section
  if (input.recommendations && input.recommendations.length > 0) {
    const recs = input.recommendations.map((r) => `- ${r}`).join("\n");
    sections.push("", "## Recommendations", "", recs);
  }

  // Footer
  sections.push("", "---", "*Generated by Jurassic Modernization Agent*");

  return sections.join("\n");
}

function getOctokit(token?: string): Octokit {
  const authToken = token ?? process.env.GITHUB_TOKEN;
  if (!authToken) {
    throw new Error(
      "GitHub token is required. Provide a token or set the GITHUB_TOKEN environment variable.",
    );
  }
  return new Octokit({ auth: authToken });
}

function handleGitHubError(err: unknown, context: string): never {
  if (err instanceof Error && "status" in err) {
    const status = (err as { status: number }).status;
    if (status === 401) {
      throw new Error(`${context}: authentication failed — check your GitHub token`);
    }
    if (status === 403) {
      throw new Error(
        `${context}: forbidden — possible rate limit or insufficient permissions`,
      );
    }
    if (status === 404) {
      throw new Error(`${context}: not found — verify owner, repo, and branch names`);
    }
    if (status === 422) {
      throw new Error(`${context}: validation failed — ${err.message}`);
    }
  }
  throw err instanceof Error ? err : new Error(String(err));
}

/** Create a branch on the fork. Override in tests for mocking. */
export async function createBranch(
  owner: string,
  repo: string,
  branchName: string,
  baseBranch: string,
  token?: string,
): Promise<void> {
  const octokit = getOctokit(token);
  try {
    const { data: ref } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${baseBranch}`,
    });
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: ref.object.sha,
    });
  } catch (err) {
    handleGitHubError(err, "createBranch");
  }
}

/** Push file changes to the branch on the fork. Override in tests for mocking. */
export async function pushFiles(
  owner: string,
  repo: string,
  branchName: string,
  files: FileChange[],
  commitMessage?: string,
  token?: string,
): Promise<void> {
  const octokit = getOctokit(token);
  try {
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${branchName}`,
    });
    const latestCommitSha = refData.object.sha;

    const { data: commitData } = await octokit.git.getCommit({
      owner,
      repo,
      commit_sha: latestCommitSha,
    });
    const baseTreeSha = commitData.tree.sha;

    const treeEntries = await Promise.all(
      files.map(async (file) => {
        if (file.changeType === "delete") {
          return {
            path: file.path,
            mode: "100644" as const,
            type: "blob" as const,
            sha: null,
          };
        }
        const { data: blob } = await octokit.git.createBlob({
          owner,
          repo,
          content: Buffer.from(file.content).toString("base64"),
          encoding: "base64",
        });
        return {
          path: file.path,
          mode: "100644" as const,
          type: "blob" as const,
          sha: blob.sha,
        };
      }),
    );

    const { data: newTree } = await octokit.git.createTree({
      owner,
      repo,
      base_tree: baseTreeSha,
      tree: treeEntries,
    });

    const message = commitMessage ?? `[Jurassic] Apply changes (${files.length} file(s))`;
    const { data: newCommit } = await octokit.git.createCommit({
      owner,
      repo,
      message,
      tree: newTree.sha,
      parents: [latestCommitSha],
    });

    await octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${branchName}`,
      sha: newCommit.sha,
    });
  } catch (err) {
    handleGitHubError(err, "pushFiles");
  }
}

/** Create a pull request from the fork branch to the upstream base. Override in tests for mocking. */
export async function createPullRequest(
  owner: string,
  repo: string,
  title: string,
  body: string,
  head: string,
  base: string,
  token?: string,
): Promise<{ prNumber: number; prUrl: string }> {
  const octokit = getOctokit(token);
  try {
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title,
      body,
      head,
      base,
    });
    return { prNumber: pr.number, prUrl: pr.html_url };
  } catch (err) {
    handleGitHubError(err, "createPullRequest");
  }
}

function validateInput(context: unknown): PrWriterInput {
  const input = context as PrWriterInput;
  if (!input || typeof input !== "object") {
    throw new Error("pr_writer: context must be an object");
  }
  if (!input.forkOwner || typeof input.forkOwner !== "string") {
    throw new Error("pr_writer: forkOwner is required");
  }
  if (!input.repoName || typeof input.repoName !== "string") {
    throw new Error("pr_writer: repoName is required");
  }
  if (!input.taskId || typeof input.taskId !== "string") {
    throw new Error("pr_writer: taskId is required");
  }
  if (!input.taskDescription || typeof input.taskDescription !== "string") {
    throw new Error("pr_writer: taskDescription is required");
  }
  if (!Array.isArray(input.fileChanges)) {
    throw new Error("pr_writer: fileChanges must be an array");
  }
  return input;
}

export const prWriterSkill: Skill = {
  name: "pr_writer",

  async execute(context: unknown): Promise<PrWriterOutput> {
    const input = validateInput(context);

    const branchName = buildBranchName(input.taskId);
    const title = buildPrTitle(input.taskDescription);
    const body = buildPrBody({
      taskDescription: input.taskDescription,
      fileChanges: input.fileChanges,
      artifactIds: input.artifactIds,
      riskItems: input.riskItems,
      recommendations: input.recommendations,
    });
    const fileCount = input.fileChanges.length;

    if (input.dryRun) {
      return {
        branchName,
        title,
        body,
        fileCount,
        status: "dry-run",
        confidence: body.length > 100 ? 0.9 : 0.7,
      };
    }

    try {
      await createBranch(input.forkOwner, input.repoName, branchName, input.baseBranch);
      await pushFiles(input.forkOwner, input.repoName, branchName, input.fileChanges);
      const { prNumber, prUrl } = await createPullRequest(
        input.forkOwner,
        input.repoName,
        title,
        body,
        `${input.forkOwner}:${branchName}`,
        input.baseBranch,
      );

      return {
        prNumber,
        prUrl,
        branchName,
        title,
        body,
        fileCount,
        status: "created",
        confidence: 0.95,
      };
    } catch (err) {
      return {
        branchName,
        title,
        body,
        fileCount,
        status: "failed",
        error: err instanceof Error ? err.message : String(err),
        confidence: 0.0,
      };
    }
  },
};
