import { describe, it, expect } from "vitest";
import {
  incrementalPrSkill,
  buildBranchName,
  buildPrTitle,
  buildPrBody,
  sanitizeBranchName,
  type IncrementalPrInput,
  type IncrementalPrOutput,
} from "../incremental_pr.js";

const baseInput: IncrementalPrInput = {
  repoPath: "/repo",
  forkOwner: "test-owner",
  forkRepo: "test-repo",
  baseBranch: "main",
  tasks: [
    {
      id: "migrate-auth",
      title: "Migrate auth module",
      description: "Move auth from legacy to new system",
      filePaths: ["src/auth.ts", "src/auth.test.ts"],
    },
  ],
};

describe("incremental_pr skill", () => {
  it("has the correct name", () => {
    expect(incrementalPrSkill.name).toBe("incremental_pr");
  });

  // --- Branch name generation ---
  describe("branch name generation", () => {
    it("creates jurassic/<taskId> branches", () => {
      expect(buildBranchName("migrate-auth")).toBe("jurassic/migrate-auth");
    });

    it("sanitizes special characters", () => {
      expect(sanitizeBranchName("foo bar!@#baz")).toBe("foo-bar-baz");
    });

    it("collapses consecutive dashes", () => {
      expect(sanitizeBranchName("a--b---c")).toBe("a-b-c");
    });

    it("trims leading/trailing dashes", () => {
      expect(sanitizeBranchName("--abc--")).toBe("abc");
    });

    it("preserves slashes and underscores", () => {
      expect(sanitizeBranchName("phase_1/task_2")).toBe("phase_1/task_2");
    });
  });

  // --- PR title ---
  describe("PR title format", () => {
    it("prefixes with [Jurassic]", () => {
      expect(buildPrTitle("Migrate auth module")).toBe(
        "[Jurassic] Migrate auth module",
      );
    });
  });

  // --- PR body ---
  describe("PR body", () => {
    it("includes description", () => {
      const body = buildPrBody({
        description: "Move auth from legacy",
        filePaths: ["src/auth.ts"],
      });
      expect(body).toContain("Move auth from legacy");
    });

    it("includes file paths", () => {
      const body = buildPrBody({
        description: "desc",
        filePaths: ["src/a.ts", "src/b.ts"],
      });
      expect(body).toContain("`src/a.ts`");
      expect(body).toContain("`src/b.ts`");
    });

    it("includes auto-generated footer", () => {
      const body = buildPrBody({ description: "d", filePaths: [] });
      expect(body).toContain("Auto-generated by Jurassic");
    });
  });

  // --- Dry-run status ---
  describe("dry-run execution", () => {
    it("returns dry-run status for all tasks", async () => {
      const result = (await incrementalPrSkill.execute(
        baseInput,
      )) as IncrementalPrOutput;
      for (const pr of result.pullRequests) {
        expect(pr.status).toBe("dry-run");
      }
    });

    it("maps task fields correctly", async () => {
      const result = (await incrementalPrSkill.execute(
        baseInput,
      )) as IncrementalPrOutput;
      const pr = result.pullRequests[0];
      expect(pr.taskId).toBe("migrate-auth");
      expect(pr.branchName).toBe("jurassic/migrate-auth");
      expect(pr.title).toBe("[Jurassic] Migrate auth module");
      expect(pr.body).toContain("src/auth.ts");
    });
  });

  // --- Validation ---
  describe("validation", () => {
    it("throws when forkOwner is missing", async () => {
      const input = { ...baseInput, forkOwner: "" };
      await expect(incrementalPrSkill.execute(input)).rejects.toThrow(
        "forkOwner is required",
      );
    });

    it("throws when forkRepo is missing", async () => {
      const input = { ...baseInput, forkRepo: "" };
      await expect(incrementalPrSkill.execute(input)).rejects.toThrow(
        "forkRepo is required",
      );
    });

    it("returns empty results for empty tasks array", async () => {
      const input = { ...baseInput, tasks: [] };
      const result = (await incrementalPrSkill.execute(
        input,
      )) as IncrementalPrOutput;
      expect(result.pullRequests).toEqual([]);
      expect(result.stats.total).toBe(0);
    });
  });

  // --- Stats ---
  describe("stats", () => {
    it("reports correct totals", async () => {
      const input: IncrementalPrInput = {
        ...baseInput,
        tasks: [
          {
            id: "t1",
            title: "Task 1",
            description: "d1",
            filePaths: ["a.ts"],
          },
          {
            id: "t2",
            title: "Task 2",
            description: "d2",
            filePaths: ["b.ts"],
          },
          {
            id: "t3",
            title: "Task 3",
            description: "d3",
            filePaths: ["c.ts"],
          },
        ],
      };
      const result = (await incrementalPrSkill.execute(
        input,
      )) as IncrementalPrOutput;
      expect(result.stats.total).toBe(3);
      expect(result.stats.created).toBe(0);
      expect(result.stats.failed).toBe(0);
    });
  });
});
