import { describe, it, expect } from "vitest";
import {
  prWriterSkill,
  buildBranchName,
  buildPrTitle,
  buildPrBody,
  type PrWriterInput,
  type PrWriterOutput,
} from "../pr_writer.js";

const baseInput: PrWriterInput = {
  forkOwner: "my-fork-user",
  repoName: "legacy-app",
  baseBranch: "main",
  taskId: "migrate-auth",
  taskDescription: "Migrate auth module to new framework",
  fileChanges: [
    { path: "src/auth.ts", content: "export class Auth {}", changeType: "modify" },
    { path: "src/auth.test.ts", content: "test('auth')", changeType: "create" },
  ],
  dryRun: true,
};

describe("pr_writer skill", () => {
  it("has the correct name", () => {
    expect(prWriterSkill.name).toBe("pr_writer");
  });

  // 1. Generates correct branch name from taskId
  it("generates correct branch name from taskId", () => {
    expect(buildBranchName("migrate-auth")).toBe("jurassic/task-migrate-auth");
    expect(buildBranchName("phase_1/step_2")).toBe("jurassic/task-phase_1/step_2");
  });

  // 2. Generates PR title with task description
  it("generates PR title with task description", () => {
    expect(buildPrTitle("Migrate auth module")).toBe("[Jurassic] Migrate auth module");
  });

  // 3. PR body includes artifacts section
  it("includes artifacts section when artifactIds provided", () => {
    const body = buildPrBody({
      taskDescription: "desc",
      fileChanges: [],
      artifactIds: ["artifact-001", "artifact-002"],
    });
    expect(body).toContain("## Artifacts Referenced");
    expect(body).toContain("`artifact-001`");
    expect(body).toContain("`artifact-002`");
  });

  // 4. PR body includes risk items table
  it("includes risk items table when riskItems provided", () => {
    const body = buildPrBody({
      taskDescription: "desc",
      fileChanges: [],
      riskItems: [
        { id: "R1", severity: "high", description: "Breaking API change" },
        { id: "R2", severity: "low", description: "Cosmetic rename" },
      ],
    });
    expect(body).toContain("## Risk Items");
    expect(body).toContain("| R1 | high | Breaking API change |");
    expect(body).toContain("| R2 | low | Cosmetic rename |");
    expect(body).toContain("| ID | Severity | Description |");
  });

  // 5. PR body includes recommendations
  it("includes recommendations when provided", () => {
    const body = buildPrBody({
      taskDescription: "desc",
      fileChanges: [],
      recommendations: ["Run integration tests", "Review auth flow"],
    });
    expect(body).toContain("## Recommendations");
    expect(body).toContain("- Run integration tests");
    expect(body).toContain("- Review auth flow");
  });

  // 6. Dry run returns PR details without creation
  it("returns dry-run status without creating anything", async () => {
    const result = (await prWriterSkill.execute(baseInput)) as PrWriterOutput;
    expect(result.status).toBe("dry-run");
    expect(result.branchName).toBe("jurassic/task-migrate-auth");
    expect(result.title).toBe("[Jurassic] Migrate auth module to new framework");
    expect(result.fileCount).toBe(2);
    expect(result.prNumber).toBeUndefined();
    expect(result.prUrl).toBeUndefined();
  });

  // 7. Handles empty file changes
  it("handles empty file changes", async () => {
    const input: PrWriterInput = { ...baseInput, fileChanges: [], dryRun: true };
    const result = (await prWriterSkill.execute(input)) as PrWriterOutput;
    expect(result.fileCount).toBe(0);
    expect(result.body).toContain("_No file changes._");
    expect(result.status).toBe("dry-run");
  });

  // 8. Fork-aware: uses forkOwner in output
  it("uses forkOwner for fork-aware operations", async () => {
    const input: PrWriterInput = { ...baseInput, forkOwner: "contributor-user" };
    const result = (await prWriterSkill.execute(input)) as PrWriterOutput;
    expect(result.status).toBe("dry-run");
    expect(result.branchName).toContain("jurassic/task-");
  });

  // Body includes footer
  it("includes auto-generated footer", () => {
    const body = buildPrBody({
      taskDescription: "desc",
      fileChanges: [],
    });
    expect(body).toContain("Generated by Jurassic Modernization Agent");
  });

  // Validation
  describe("validation", () => {
    it("throws when forkOwner is missing", async () => {
      const input = { ...baseInput, forkOwner: "" };
      await expect(prWriterSkill.execute(input)).rejects.toThrow("forkOwner is required");
    });

    it("throws when repoName is missing", async () => {
      const input = { ...baseInput, repoName: "" };
      await expect(prWriterSkill.execute(input)).rejects.toThrow("repoName is required");
    });

    it("throws when taskId is missing", async () => {
      const input = { ...baseInput, taskId: "" };
      await expect(prWriterSkill.execute(input)).rejects.toThrow("taskId is required");
    });
  });
});
